### ISSUE TITLE
仍然是解析视频说脚本错误

### ISSUE THREAD

**Issue by legendtang** [Syndim/XBMC-Bilibili#6]
运行的是 raspbmc，xmbc 13.2
相关log

08:18:37 T:3037066016   ERROR: GetDirectory - Error getting plugin://plugin.video.letv/
08:18:37 T:3037066016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.letv/) failed
08:18:38 T:2846680128  NOTICE: Thread BackgroundLoader start, auto delete: false
08:18:40 T:2846680128  NOTICE: Thread LanguageInvoker start, auto delete: false
08:18:40 T:2846680128  NOTICE: -->Python Interpreter Initialized<--
08:18:44 T:2846680128  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
08:18:44 T:2773300288  NOTICE: Thread BackgroundLoader start, auto delete: false
08:18:46 T:2846680128  NOTICE: Thread LanguageInvoker start, auto delete: false
08:18:46 T:2846680128  NOTICE: -->Python Interpreter Initialized<--
08:19:04 T:2846680128  NOTICE: [xbmcswift2] Request for "/items/RSS/" matches rule for function "show_target_items"
08:19:04 T:2846680128  NOTICE: [Bilibili]: Getting items by type
08:19:04 T:2773300288  NOTICE: Thread BackgroundLoader start, auto delete: false
08:19:06 T:2846680128  NOTICE: Thread LanguageInvoker start, auto delete: false
08:19:06 T:2846680128  NOTICE: -->Python Interpreter Initialized<--
08:19:10 T:2846680128  NOTICE: [xbmcswift2] Request for "/items/RSS/series/" matches rule for function "show_category_items"
08:19:10 T:2846680128  NOTICE: [Bilibili]: Getting items by type
08:19:10 T:2846680128  NOTICE: [Bilibili]: Getting RSS Items
08:19:27 T:2846680128  NOTICE: [Bilibili]: RSS Items fetched succeeded!
08:19:28 T:2773300288  NOTICE: Thread BackgroundLoader start, auto delete: false
08:20:07 T:2792354880  NOTICE: ES: Client  from 192.168.1.244 timed out
08:22:39 T:2834297920  NOTICE: Thread JobWorker start, auto delete: true
08:22:39 T:2817520704  NOTICE: Thread LanguageInvoker start, auto delete: false
08:22:39 T:2817520704  NOTICE: -->Python Interpreter Initialized<--
08:22:41 T:2817520704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SystemError'>
                                            Error Contents: dynamic module not initialized properly
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/XBMC-Bilibili-master/addon.py", line 4, in <module>
                                                from resources.lib.bilibili import Bili
                                              File "/home/pi/.xbmc/addons/XBMC-Bilibili-master/resources/lib/bilibili.py", line 4, in <module>
                                                import feedparser
                                              File "/home/pi/.xbmc/addons/XBMC-Bilibili-master/resources/lib/feedparser.py", line 199, in <module>
                                                xml.sax.make_parser(PREFERRED_XML_PARSERS) # test for valid parsers
                                              File "/usr/lib/python2.7/xml/sax/**init**.py", line 81, in make_parser
                                                return _create_parser(parser_name)
                                              File "/usr/lib/python2.7/xml/sax/__init__.py", line 105, in _create_parser
                                                drv_module = __import__(parser_name,{},{},['create_parser'])
                                              File "/usr/lib/python2.7/dist-packages/drv_libxml2.py", line 67, in <module>
                                                import libxml2
                                              File "/usr/lib/python2.7/dist-packages/libxml2.py", line 1, in <module>
                                                import libxml2mod
                                            SystemError: dynamic module not initialized properly
                                            -->End of Python script error report<--
08:22:41 T:3037066016   ERROR: GetDirectory - Error getting plugin://plugin.video.bilibili/videos/1455479/
08:22:41 T:3037066016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bilibili/videos/1455479/) failed
08:22:41 T:2817520704  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by aodzip** [comment]
我的raspbmc在启动插件的时候就脚本错误了…

**Comment by legendtang** [comment]
@aodzip 嗯，我也遇到过，只要出错一遍就完全进不去了
这个时候要重启一下XBMC（不过五十步笑百步），你是XBMC什么版本？

**Comment by Syndim** [comment]
从log来看，应该是raspbmc的libxml2库有问题。

**Comment by legendtang** [comment]
@Syndim 新版的话应该只能做兼容了，是要重写XBMC-Bilibili / resources / lib / feedparser.py这段？

try:
    import xml.sax
    from xml.sax.saxutils import escape as _xmlescape
except ImportError:
    _XML_AVAILABLE = 0
    def _xmlescape(data,entities={}):
        data = data.replace('&', '&amp;')
        data = data.replace('>', '&gt;')
        data = data.replace('<', '&lt;')
        for char, entity in entities:
            data = data.replace(char, entity)
        return data
else:
    try:
        xml.sax.make_parser(PREFERRED_XML_PARSERS) # test for valid parsers
    except xml.sax.SAXReaderNotAvailable:
        _XML_AVAILABLE = 0
    else:
        _XML_AVAILABLE = 1

**Comment by zmj1316** [comment]
脚本错误+1
14:18:06 T:139668140021504  NOTICE: -->Python Interpreter Initialized<--
14:18:06 T:139668140021504  NOTICE: [xbmcswift2] Request for "/items/Index/anime2/Month/" matches rule for function "show_index_items"
14:18:06 T:139668140021504  NOTICE: [Bilibili]: Getting Index Items
14:18:13 T:139668140021504  NOTICE: [Bilibili]: Index files fetched succeeded!
14:18:13 T:139668140021504  NOTICE: [Bilibili]: Index items fetched succeeded!
14:18:13 T:139668131497728  NOTICE: Thread BackgroundLoader start, auto delete: false
14:18:16 T:139669141161728  NOTICE: Thread LanguageInvoker start, auto delete: false
14:18:16 T:139669141161728  NOTICE: -->Python Interpreter Initialized<--
14:18:16 T:139669141161728  NOTICE: [xbmcswift2] Request for "/items/Index/anime2/Month/2014-10/" matches rule for function "show_items_by_ident"
14:18:16 T:139669141161728  NOTICE: [Bilibili]: Getting items from cache
14:18:16 T:139669141161728  NOTICE: [Bilibili]: Index files already exists!
14:18:17 T:139669141161728  NOTICE: [Bilibili]: Cached items fetched succeeded!
14:18:17 T:139669141161728  NOTICE: Thread BackgroundLoader start, auto delete: false
14:18:27 T:139669141161728  NOTICE: Thread LanguageInvoker start, auto delete: false
14:18:27 T:139669141161728  NOTICE: -->Python Interpreter Initialized<--
14:18:27 T:139669141161728  NOTICE: [xbmcswift2] Request for "/videos/1593998/" matches rule for function "show_video_list"
14:18:32 T:139668131497728  NOTICE: Thread BackgroundLoader start, auto delete: false
14:18:36 T:139668140021504  NOTICE: Thread LanguageInvoker start, auto delete: false
14:18:36 T:139668140021504  NOTICE: -->Python Interpreter Initialized<--
14:18:36 T:139668140021504  NOTICE: [xbmcswift2] Request for "/video/video%2Fav1593998%2F/0/1/" matches rule for function "play_video"
14:18:36 T:139668140021504  NOTICE: [BiliAddon]: Fetch subtitle
14:18:36 T:139668140021504  NOTICE: [Bilibili]: Getting video address
14:18:36 T:139668140021504  NOTICE: [Bilibili]: Page url: http://www.bilibili.com/video/av1593998/
14:18:41 T:139668140021504  NOTICE: [Bilibili]: Origin page length: 24693
14:18:41 T:139668140021504  NOTICE: [Bilibili]: Parsing page
14:18:41 T:139668140021504  NOTICE: [Bilibili]: Interface url: http://interface.bilibili.com/playurl?cid=2421806
14:18:41 T:139668140021504  NOTICE: [Bilibili]: Getting video address by interface page
14:18:46 T:139668140021504  NOTICE: [Bilibili]: Interface page length: 66
14:18:46 T:139668140021504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.parsers.expat.ExpatError'>
                                            Error Contents: not well-formed (invalid token): line 1, column 0
                                            Traceback (most recent call last):
                                              File "/home/zmj/.xbmc/addons/XBMC-Bilibili-master/addon.py", line 204, in <module>
                                                plugin.run()
                                              File "/home/zmj/.xbmc/addons/XBMC-Bilibili-master/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/zmj/.xbmc/addons/XBMC-Bilibili-master/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/zmj/.xbmc/addons/XBMC-Bilibili-master/addon.py", line 193, in play_video
                                                playlist = bili.get_video_urls(url, True)
                                              File "/home/zmj/.xbmc/addons/XBMC-Bilibili-master/resources/lib/bilibili.py", line 248, in get_video_urls
                                                return self._parse_urls(page_content, need_subtitle)
                                              File "/home/zmj/.xbmc/addons/XBMC-Bilibili-master/resources/lib/bilibili.py", line 87, in _parse_urls
                                                doc = minidom.parseString(content)
                                              File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1928, in parseString
                                                return expatbuilder.parseString(string)
                                              File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
                                                return builder.parseString(string)
                                              File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
                                                parser.Parse(string, True)
                                            ExpatError: not well-formed (invalid token): line 1, column 0
                                            -->End of Python script error report<--
14:18:46 T:139669149554432  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
14:18:46 T:139669639997632   ERROR: GetDirectory - Error getting plugin://plugin.video.bilibili/video/video%2Fav1593998%2F/0/1/
14:18:46 T:139669639997632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bilibili/video/video%2Fav1593998%2F/0/1/) failed
14:18:46 T:139668140021504  NOTICE: Thread BackgroundLoader start, auto delete: false
14:18:51 T:139668140021504  NOTICE: Thread LanguageInvoker start, auto delete: false

**Comment by Syndim** [comment]
@zmj1316 看来是B站改了接口，待我有空再看看怎么解决吧。
